---
services:
  postgres:
    container_name: ticket-purchasing-system-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  order-service:
    container_name: ticket-purchasing-system-orders
    image: dachereukho17/ticket-purchasing-system-orders
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  auth-service:
    container_name: ticket-purchasing-system-auth
    image: dachereukho17/ticket-purchasing-system-auth
    ports:
      - "8081:8081"
    depends_on:
      - postgres