server:
  port: 8081

spring:
  application:
    name: auth-app

  main:
    banner-mode: "off"

  datasource:
    url: jdbc:postgresql://ticket-purchasing-system-db:5432/postgres
    username: postgres
    password: postgres

jwt:
  key: bcb37123b6cb7891263cb97126cb978123
  access-token-expiration: 3600000